{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "c5fda30b_3fc51760",
        "filename": "/COMMIT_MSG",
        "patchSetId": 7
      },
      "lineNbr": 36,
      "author": {
        "id": 1000338
      },
      "writtenOn": "2022-03-02T04:10:00Z",
      "side": 1,
      "message": "Why isn\u0027t there a callout?",
      "range": {
        "startLine": 30,
        "startChar": 0,
        "endLine": 36,
        "endChar": 1
      },
      "revId": "a8ba5e6b08e31ac7b1729e6ccc318cf58396f695",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "07c6776f_976b60a4",
        "filename": "ibm_vpd_app.cpp",
        "patchSetId": 7
      },
      "lineNbr": 408,
      "author": {
        "id": 1000338
      },
      "writtenOn": "2022-03-02T04:10:00Z",
      "side": 1,
      "message": "I wonder if this is really needed. Don\u0027t the IIC_BUS and IIC_ADDR show up in the final PEL without having to append it top the message?",
      "range": {
        "startLine": 408,
        "startChar": 3,
        "endLine": 408,
        "endChar": 25
      },
      "revId": "a8ba5e6b08e31ac7b1729e6ccc318cf58396f695",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "1bd17071_564151ee",
        "filename": "ibm_vpd_app.cpp",
        "patchSetId": 7
      },
      "lineNbr": 480,
      "author": {
        "id": 1000338
      },
      "writtenOn": "2022-03-02T04:10:00Z",
      "side": 1,
      "message": "This throw will not be caught in the catch block at 483. In order for that to work, you\u0027ll have to have another try block around lines 457 through 481. Since we are anyway throwing a GPIOexception from line 480, why not simply treat a system_error as a GPIO exception and call logGpioPel?",
      "revId": "a8ba5e6b08e31ac7b1729e6ccc318cf58396f695",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "ef16826d_b9c6946e",
        "filename": "ibm_vpd_app.cpp",
        "patchSetId": 7
      },
      "lineNbr": 577,
      "author": {
        "id": 1000338
      },
      "writtenOn": "2022-03-02T04:10:00Z",
      "side": 1,
      "message": "See comment above about this throw.",
      "revId": "a8ba5e6b08e31ac7b1729e6ccc318cf58396f695",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}