{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "6f54635f_fd879bb3",
        "filename": "vpd-manager/include/utility/vpd_specific_utility.hpp",
        "patchSetId": 7
      },
      "lineNbr": 146,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2025-02-21T10:25:47Z",
      "side": 1,
      "message": "Do we need this at this scope. We can reduce the scope by returning from try and hence will also not need clear in the catch.",
      "revId": "ac1045205a04673e183419912ec98f0049b3fdce",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "7638a67f_94c1472e",
        "filename": "vpd-manager/src/backup_restore.cpp",
        "patchSetId": 7
      },
      "lineNbr": 250,
      "author": {
        "id": 1000522
      },
      "writtenOn": "2025-02-21T10:25:47Z",
      "side": 1,
      "message": "earlier this API was throwing, so any error would have stopped processing. Now how that is being handled?",
      "revId": "ac1045205a04673e183419912ec98f0049b3fdce",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}